export const REGISTRAR_USUARIO = "REGISTRAR_USUARIO";

export const REGISTRAR_USUARIO_EXITO = "REGISTRAR_USUARIO_EXITO";

export const REGISTRAR_USUARIO_ERROR = "REGISTRAR_USUARIO_ERROR";

export const LOGIN_USUARIO = "LOGIN_USUARIO";

export const LOGIN_USUARIO_EXITO = "LOGIN_USUARIO_EXITO";

export const LOGIN_USUARIO_ERROR = "LOGIN_USUARIO_ERROR";

export const CONFIRMADOS_GLOBALES = "CONFIRMADOS_GLOBALES";

export const CONFIRMADOS_GLOBALES_EXITO = "CONFIRMADOS_GLOBALES_EXITO";

export const CONFIRMADOS_GLOBALES_ERROR = "CONFIRMADOS_GLOBALES_ERROR";

export const GRAFICA_GLOBAL_CARGA = "GRAFICA_GLOBAL_CARGA";

export const GRAFICA_GLOBAL_EXITO = "GRAFICA_GLOBAL_EXITO";

export const GRAFICA_GLOBAL_ERROR = "GRAFICA_GLOBAL_ERROR";

export const GRAFICA_PERU_CARGA = "GRAFICA_PERU_CARGA";

export const GRAFICA_PERU_EXITO = "GRAFICA_PERU_EXITO";

export const GRAFICA_PERU_ERROR = "GRAFICA_PERU_ERROR";

export const GRAFICA_ACTUAL_EXITO2 = "GRAFICA_ACTUAL_EXITO2";

export const GRAFICA_ACTUAL_EXITO = "GRAFICA_ACTUAL_EXITO";

export const P_DATA_PERU = "P_DATA_PERU";

export const P_DATA_CARTA_GLOBAL = "P_DATA_CARTA_GLOBAL";

export const P_DATA_GRAFICO_GLOBAL = "P_DATA_GRAFICO_GLOBAL";

export const FILTRO_CARTA_COVID = "FILTRO_CARTA_COVID";

export const FILTRO_GRAFICO_COVID = "FILTRO_GRAFICO_COVID";

export const FILTRO_DASHBOARD = "FILTRO_DASHBOARD";

export const FILTRO_PREGUNTAS = "FILTRO_PREGUNTAS";

export const FILTRO_USUARIOS = "FILTRO_USUARIOS";

export const FILTRO_PERFIL = "FILTRO_PERFIL";

export const FILTRO_AGREGAR_PREGUNTA = "FILTRO_AGREGAR_PREGUNTA";

export const CARGAR_DATA_NOTICIAS = "CARGAR_DATA_NOTICIAS";

export const DATA_NOTICIAS_EXITO = "DATA_NOTICIAS_EXITO";

export const DATA_NOTICIAS_ERROR = "DATA_NOTICIAS_ERROR";

export const VALIDAR_TOKEN = "VALIDAR_TOKEN";

export const FILTRO_LOGIN_ADMIN = "FILTRO_LOGIN_ADMIN";

export const FILTRO_ERROR = "FILTRO_ERROR";

export const VALIDAR_AUTENTICACION = "VALIDAR_AUTENTICACION";

//export const CARGAR_DATOS_USUARIO_AUTENTICADO =
//  "CARGAR_DATOS_USUARIO_AUTENTICADO";
export const ERROR_AUTENTICACION = "ERROR_AUTENTICACION";

export const AÑADIR_INFORMACION_CARGA = "AÑADIR_INFORMACION_CARGA";

export const AÑADIR_INFORMACION_EXITO = "AÑADIR_INFORMACION_EXITO";

export const AÑADIR_INFORMACION_ERROR = "AÑADIR_INFORMACION_ERROR";

export const MOSTRAR_CUESTIONARIO = "MOSTRAR_CUESTIONARIO";

export const MOSTRAR_CUESTIONARIO_CARGA = "MOSTRAR_CUESTIONARIO_CARGA";

export const MOSTRAR_CUESTIONARIO_ERROR = "MOSTRAR_CUESTIONARIO_ERROR";

export const CARGAR_CUESTIONARIO = "CARGAR_CUESTIONARIO";

export const CREAR_CUESTIONARIO = "CREAR_CUESTIONARIO";

export const ERROR_CUESTIONARIO = "ERROR_CUESTIONARIO";

export const OBTENER_PREGUNTAS = "OBTENER_PREGUNTAS";

export const OBTENER_PREGUNTAS_EXITO = "OBTENER_PREGUNTAS_EXITO";

export const OBTENER_PREGUNTAS_ERROR = "OBTENER_PREGUNTAS_ERROR";

export const BORRAR_CUESTIONARIO = "BORRAR_CUESTIONARIO";

export const BORRAR_ESTADO = "BORRAR_ESTADO";

export const BORRAR_ESTADO_RESPUESTA = "BORRAR_ESTADO_RESPUESTA";

export const CARGAR_PAGINA = "CARGAR_PAGINA";

export const PAGINA_INICIAL = "PAGINA_INICIAL";

//export const BORRAR_CUESTIONARIO = "BORRAR_CUESTIONARIO";

//export const BORRAR_CUESTIONARIO = "BORRAR_CUESTIONARIO";

//export const BORRAR_CUESTIONARIO = "BORRAR_CUESTIONARIO";

export const MANDAR_RESPUESTA = "MANDAR_RESPUESTA";
