export const REGISTRAR_USUARIO = "REGISTRAR_USUARIO";

export const REGISTRAR_USUARIO_EXITO = "REGISTRAR_USUARIO_EXITO";

export const REGISTRAR_USUARIO_ERROR = "REGISTRAR_USUARIO_ERROR";

export const LOGIN_USUARIO = "LOGIN_USUARIO";

export const LOGIN_USUARIO_EXITO = "LOGIN_USUARIO_EXITO";

export const LOGIN_USUARIO_ERROR = "LOGIN_USUARIO_ERROR";
