export const REGISTRAR_USUARIO = "REGISTRAR_USUARIO";

export const REGISTRAR_USUARIO_EXITO = "REGISTRAR_USUARIO_EXITO";

export const REGISTRAR_USUARIO_ERROR = "REGISTRAR_USUARIO_ERROR";

export const LOGIN_USUARIO = "LOGIN_USUARIO";

export const LOGIN_USUARIO_EXITO = "LOGIN_USUARIO_EXITO";

export const LOGIN_USUARIO_ERROR = "LOGIN_USUARIO_ERROR";

export const CONFIRMADOS_GLOBALES = "CONFIRMADOS_GLOBALES";

export const CONFIRMADOS_GLOBALES_EXITO = "CONFIRMADOS_GLOBALES_EXITO";

export const CONFIRMADOS_GLOBALES_ERROR = "CONFIRMADOS_GLOBALES_ERROR";

export const GRAFICA_GLOBAL_CARGA = "GRAFICA_GLOBAL_CARGA";

export const GRAFICA_GLOBAL_EXITO = "GRAFICA_GLOBAL_EXITO";

export const GRAFICA_GLOBAL_ERROR = "GRAFICA_GLOBAL_ERROR";

export const GRAFICA_PERU_CARGA = "GRAFICA_PERU_CARGA";

export const GRAFICA_PERU_EXITO = "GRAFICA_PERU_EXITO";

export const GRAFICA_PERU_ERROR = "GRAFICA_PERU_ERROR";

export const GRAFICA_ACTUAL_EXITO2 = "GRAFICA_ACTUAL_EXITO2";

export const GRAFICA_ACTUAL_EXITO = "GRAFICA_ACTUAL_EXITO";
